version: "2.2"
services:
  webserver:
    restart: always
    ports:
      - 8095:80
    build: .
    volumes:
      - ./files:/var/www/html
    environment:
      - URL=https://cesium.one/i/
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=4096M
